# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/service.proto\x12\x07rag_rpc\"7\n\x0c\x41udioRequest\x12\x15\n\raudio_content\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"M\n\x15TranscriptionResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"7\n\rIngestRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\"Q\n\x0eIngestResponse\x12\x18\n\x10\x63hunks_processed\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2R\n\x0bTranscriber\x12\x43\n\nTranscribe\x12\x15.rag_rpc.AudioRequest\x1a\x1e.rag_rpc.TranscriptionResponse2M\n\x08Ingestor\x12\x41\n\x0eIngestDocument\x12\x16.rag_rpc.IngestRequest\x1a\x17.rag_rpc.IngestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=33
  _globals['_AUDIOREQUEST']._serialized_end=88
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_start=90
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_end=167
  _globals['_INGESTREQUEST']._serialized_start=169
  _globals['_INGESTREQUEST']._serialized_end=224
  _globals['_INGESTRESPONSE']._serialized_start=226
  _globals['_INGESTRESPONSE']._serialized_end=307
  _globals['_TRANSCRIBER']._serialized_start=309
  _globals['_TRANSCRIBER']._serialized_end=391
  _globals['_INGESTOR']._serialized_start=393
  _globals['_INGESTOR']._serialized_end=470
# @@protoc_insertion_point(module_scope)
